apiVersion: app.drift.com/v1alpha1
kind: ZooKeeper
metadata:
  name: zk-cluster
  namespace: one1
spec:
  size: 3
  minSize: 1
  clientPort: 2181
  serverPort: 2888
  leaderPort: 3888
  pvcName: "zookeeper-pvc"
  dataDir: /var/lib/zookeeper
