apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: driftinits.app.drift.com
spec:
  group: app.drift.com
  names:
    kind: DriftInit
    listKind: DriftInitList
    plural: driftinits
    singular: driftinit
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DriftInit is the Schema for the driftinits API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DriftInitSpec defines the desired state of DriftInit
            type: object
            properties:
              namespace:
                type: string
              components:
                type: array
                items:
                  type: string
              currentPath:
                type: string
              active:
                format: int32
                type: integer
              complete:
                type: boolean
              pvc:
                type: object
                properties:
                  ZooKeeper:
                    type: object
                    properties:
                      storageClass:
                        type: string
                      storage:
                        type: string
          status:
            description: DriftInitStatus defines the observed state of DriftInit
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
