apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkas.app.drift.com
spec:
  group: app.drift.com
  names:
    kind: Kafka
    listKind: KafkaList
    plural: kafkas
    singular: kafka
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Kafka is the Schema for the kafkas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KafkaSpec defines the desired state of Kafka
            type: object
            properties:
              namespace:
                type: string
              size:
                format: int32
                type: integer
              minSize:
                format: int32
                type: integer
              clientPort:
                format: int32
                type: integer
              dataDir:
                type: string
              zookeeperAddress:
                type: string
              storage:
                type: string
              storageClass:
                type: string
          status:
            description: KafkaStatus defines the observed state of Kafka
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
