apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift
spec:
  replicas: 3
  selector:
    matchLabels:
      name: drift
  template:
    metadata:
      labels:
        name: drift
    spec:
      serviceAccountName: drift
      containers:
        - name: drift
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - drift
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "drift"
