kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drift
subjects:
- kind: ServiceAccount
  name: drift
roleRef:
  kind: Role
  name: drift
  apiGroup: rbac.authorization.k8s.io
