// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftInit) DeepCopyInto(out *DriftInit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftInit.
func (in *DriftInit) DeepCopy() *DriftInit {
	if in == nil {
		return nil
	}
	out := new(DriftInit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftInitList) DeepCopyInto(out *DriftInitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriftInit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftInitList.
func (in *DriftInitList) DeepCopy() *DriftInitList {
	if in == nil {
		return nil
	}
	out := new(DriftInitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftInitSpec) DeepCopyInto(out *DriftInitSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftInitSpec.
func (in *DriftInitSpec) DeepCopy() *DriftInitSpec {
	if in == nil {
		return nil
	}
	out := new(DriftInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftInitStatus) DeepCopyInto(out *DriftInitStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftInitStatus.
func (in *DriftInitStatus) DeepCopy() *DriftInitStatus {
	if in == nil {
		return nil
	}
	out := new(DriftInitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZooKeeper) DeepCopyInto(out *ZooKeeper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZooKeeper.
func (in *ZooKeeper) DeepCopy() *ZooKeeper {
	if in == nil {
		return nil
	}
	out := new(ZooKeeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZooKeeperList) DeepCopyInto(out *ZooKeeperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZooKeeper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZooKeeperList.
func (in *ZooKeeperList) DeepCopy() *ZooKeeperList {
	if in == nil {
		return nil
	}
	out := new(ZooKeeperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZooKeeperSpec) DeepCopyInto(out *ZooKeeperSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZooKeeperSpec.
func (in *ZooKeeperSpec) DeepCopy() *ZooKeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ZooKeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZooKeeperStatus) DeepCopyInto(out *ZooKeeperStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZooKeeperStatus.
func (in *ZooKeeperStatus) DeepCopy() *ZooKeeperStatus {
	if in == nil {
		return nil
	}
	out := new(ZooKeeperStatus)
	in.DeepCopyInto(out)
	return out
}
